### ISSUE TITLE
请问下这个glsl文件在Android 的mpv上支持吗

### ISSUE THREAD

**Issue by langxuelang** [TianZerL/ACNetGLSL#10]
我在android mpv试了下，好像没有生效，不知道是不是不支持Android

**Comment by TianZerL** [comment]
理论上支持，但是因为安卓opengl有多种实现的原因，具体机型需要测试才知道。一般不支持的原因是某些opengl实现对某些语法不支持，对症修改。

你可以参考anime4k项目对此的一些讨论 bloc97/Anime4K#99

**Comment by langxuelang** [comment]
收到，感谢回复


在 2024年3月15日 ***@***.***> 写道：


理论上支持，但是因为安卓opengl有多种实现的原因，具体机型需要测试才知道。一般不支持的原因是某些opengl实现对某些语法不支持，对症修改。
你可以参考anime4k项目对此的一些讨论 bloc97/Anime4K#99

**Comment by langxuelang** [comment]
@TianZerL 经过尝试我发现是Android的mpv中，如果开启软解，那么ACNetGLSL可以生效。如果是硬解则无法生效。

![3901710491756_ pic](https://github.com/TianZerL/ACNetGLSL/assets/1763538/0d7490f1-d4cd-4f08-b775-c8217be40a14)
![3891710491755_ pic](https://github.com/TianZerL/ACNetGLSL/assets/1763538/79caf178-25b0-49d7-b63e-3810373b6f70)

我的手机是三星S21

**Comment by TianZerL** [comment]
有的实现可能硬解码下数据根本不会经过mpv的shader处理，比如nvidia shield TV开硬解码会启用自己的AI upscale算法。

可以尝试更换其他后端，比如vulkan，或开启copy-back `hwdec=auto-copy`。

**Comment by langxuelang** [comment]
@TianZerL  开启copy-back后，可以了，非常感谢
